# 1 "txInterpTest.cudafe1.gpu"
# 211 "/usr/lib/gcc/x86_64-linux-gnu/4.4.3/include/stddef.h" 3
typedef unsigned long size_t;
#include "crt/host_runtime.h"
void *memcpy(void*, const void*, size_t); void *memset(void*, int, size_t);
# 399 "txInterpTest.cu"
extern int fdivide();
# 107 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f0A,texRef_f0A);
# 108 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f1A,texRef_f1A);
# 109 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f2A,texRef_f2A);
# 110 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f3A,texRef_f3A);
# 111 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f4A,texRef_f4A);
# 112 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f5A,texRef_f5A);
# 113 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f6A,texRef_f6A);
# 114 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f7A,texRef_f7A);
# 115 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f8A,texRef_f8A);
# 117 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f0B,texRef_f0B);
# 118 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f1B,texRef_f1B);
# 119 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f2B,texRef_f2B);
# 120 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f3B,texRef_f3B);
# 121 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f4B,texRef_f4B);
# 122 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f5B,texRef_f5B);
# 123 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f6B,texRef_f6B);
# 124 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f7B,texRef_f7B);
# 125 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f8B,texRef_f8B);
# 127 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f0C,texRef_f0C);
# 128 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f1C,texRef_f1C);
# 129 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f2C,texRef_f2C);
# 130 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f3C,texRef_f3C);
# 131 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f4C,texRef_f4C);
# 132 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f5C,texRef_f5C);
# 133 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f6C,texRef_f6C);
# 134 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f7C,texRef_f7C);
# 135 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f8C,texRef_f8C);
# 137 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f0D,texRef_f0D);
# 138 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f1D,texRef_f1D);
# 139 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f2D,texRef_f2D);
# 140 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f3D,texRef_f3D);
# 141 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f4D,texRef_f4D);
# 142 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f5D,texRef_f5D);
# 143 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f6D,texRef_f6D);
# 144 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f7D,texRef_f7D);
# 145 "txInterpTest.cu"
__loc_sc__(__text__,,) __texture_type__ __text_var(texRef_f8D,texRef_f8D);

#include "txInterpTest.cudafe2.stub.c"
